# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapReduce.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmapReduce.proto\x12\tmapreduce\"\x8d\x01\n\nMapRequest\x12\x10\n\x08startIdx\x18\x01 \x01(\x05\x12\x0e\n\x06\x65ndIdx\x18\x02 \x01(\x05\x12\x0f\n\x07iterNum\x18\x03 \x01(\x05\x12\x10\n\x08reducers\x18\x04 \x01(\x05\x12\x10\n\x08mapperID\x18\x05 \x01(\x05\x12\x13\n\x0b\x63\x65ntroids_x\x18\x06 \x03(\x01\x12\x13\n\x0b\x63\x65ntroids_y\x18\x07 \x03(\x01\"\x1d\n\x0bMapResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"]\n\rReduceRequest\x12\x0f\n\x07iterNum\x18\x01 \x01(\x05\x12\x11\n\treducerId\x18\x02 \x01(\x05\x12\x17\n\x0ftargetReducerId\x18\x03 \x01(\x05\x12\x0f\n\x07mappers\x18\x04 \x01(\x05\"@\n\x0eReduceResponse\x12\x1e\n\x05pairs\x18\x01 \x03(\x0b\x32\x0f.mapreduce.Pair\x12\x0e\n\x06status\x18\x02 \x01(\t\"6\n\x0fMapPairsRequest\x12\x11\n\treducerId\x18\x01 \x01(\x05\x12\x10\n\x08mapperId\x18\x02 \x01(\x05\"2\n\x10MapPairsResponse\x12\x1e\n\x05pairs\x18\x01 \x03(\x0b\x32\x0f.mapreduce.Pair\"0\n\x04Pair\x12\x12\n\ncentroidId\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x32\xe8\x01\n\x10MapReduceService\x12=\n\nProcessMap\x12\x15.mapreduce.MapRequest\x1a\x16.mapreduce.MapResponse\"\x00\x12\x46\n\rProcessReduce\x12\x18.mapreduce.ReduceRequest\x1a\x19.mapreduce.ReduceResponse\"\x00\x12M\n\x10RetrieveMapPairs\x12\x1a.mapreduce.MapPairsRequest\x1a\x1b.mapreduce.MapPairsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapReduce_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MAPREQUEST']._serialized_start=31
  _globals['_MAPREQUEST']._serialized_end=172
  _globals['_MAPRESPONSE']._serialized_start=174
  _globals['_MAPRESPONSE']._serialized_end=203
  _globals['_REDUCEREQUEST']._serialized_start=205
  _globals['_REDUCEREQUEST']._serialized_end=298
  _globals['_REDUCERESPONSE']._serialized_start=300
  _globals['_REDUCERESPONSE']._serialized_end=364
  _globals['_MAPPAIRSREQUEST']._serialized_start=366
  _globals['_MAPPAIRSREQUEST']._serialized_end=420
  _globals['_MAPPAIRSRESPONSE']._serialized_start=422
  _globals['_MAPPAIRSRESPONSE']._serialized_end=472
  _globals['_PAIR']._serialized_start=474
  _globals['_PAIR']._serialized_end=522
  _globals['_MAPREDUCESERVICE']._serialized_start=525
  _globals['_MAPREDUCESERVICE']._serialized_end=757
# @@protoc_insertion_point(module_scope)
